name: 打包应用并上传阿里云

on:
    push:
        branches:
            - master

jobs:
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: ubuntu-latest
        steps:
            # 获取源码
            - name: 迁出代码
              # 使用action库  actions/checkout获取源码
              uses: actions/checkout@master

            - name: 设置Bun
              uses: oven-sh/setup-bun@v1
              with:
                bun-version: latest
               
            # 上传阿里云
            - name: 发布到腾讯云
              uses: easingthemes/ssh-deploy@v2.1.1
              env:
                  # 私钥
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  # scp参数
                  ARGS: '-avzr --delete'
                  # 源目录
                  SOURCE: 'src/'
                  # 服务器ip：换成你的服务器IP
                  REMOTE_HOST: ${{ secrets.SERVER_HOST }}
                  # 用户
                  REMOTE_USER: 'root'
                  # 目标地址
                  TARGET: '/www/wwwroot/firstHonoApi/src'
