name: 博客后台部署 (手动触发)

# 手动触发器
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 删除旧的文件
      - name: 清空旧项目文件
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "清空旧的文件..."
            rm -rf /www/wwwroot/firstHonoApi/src/*
            echo "删除完成"

      # 上传当前项目中的 src 路径下的文件
      - name: 上传 src 路径下的文件
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "src/"  # 修改为上传 src 目录
          target: "/www/wwwroot/firstHonoApi"  # 目标路径
          strip_components: 1  # 删除源路径中的第一层目录（即 src 目录）
